/** Declaration file generated by dts-gen */
// TODO: add specific quality and resolution values like 1080p60 etc.
export interface VideoInfo {
    quality: string;
    resolution?: string;
    url: string;
}

export function getStream(channel: string, raw?: boolean): Array<VideoInfo> | string;

export function getVod(vid: string, raw?: boolean): Array<VideoInfo> | string;
